<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-29T19:59:39+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Income Focus Portfolio Management',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1458593856,
        'latest_version' => '5.7.5.6',
        'do_page_reindex_check' => false,
        'favicon_fid' => '4',
        'iphone_home_screen_thumbnail_fid' => '5',
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
);
